### ISSUE TITLE
[3.4] Add Edit to Context Menu Entries

### ISSUE THREAD

**Issue by opticyclic** [NikoKrause/CinnVIIStarkMenu#13]
I would like to see a context menu to the menu entries.
The main one I am interested in is `Open file location` for when I have manually installed some files and put them in the menu.
Sometimes I have command line switches so I want to check what they are or modify them so an `Edit` command would be good.
Another useful one might be `Uninstall` for those that are installed via a package manager.

**Comment by NikoKrause** [comment]
I don't know, if I understand, what you mean.
There is a context menu for applications. And in the context menu there is an uninstall option.

Which location should be opened?

What are command line switches? And what files do you want to edit?

**Comment by ghost** [comment]
@NikoKrause i think, what he want, it's a way for edit the execution point of the desktop file that it's represented by the menu item, or directly the desktop file if really exist. In other words, he don't like the cinnamon menu editor (this python program), and he want to be integrate this ability to the menu....

This is something that at less for now i considered unnecessary, but anyway.

**Comment by NikoKrause** [comment]
Something like Odyseus has in his CustomMenu? He has entries in the context menu to open the .desktop file.

But what's with the uninstall button?
There is one in the context menu.

**Comment by ghost** [comment]
@NikoKrause He sure don't see the uninstall button... I also don't see what Odyseus has... I will need to take a time to see what you do guy's, you also sure will have several interesting things. I only track the work of scollings, because he was the only one that create interesting things to me outside the cinnamon scope... Now you and Odyseus are doing a lot of things... Thats good... I need the time to see...

**Comment by NikoKrause** [comment]
Since there is no response from the original poster, I'm closing this.

@lestcape 
Thanks for trying to explain what opticyclic might meant. But he doesn't seem interested in explaining what he really means. Everything else seems to be a guessing game to me.

It can be reopened, if there is still interest in this and if I get more information, what the feature request is really about.

**Comment by opticyclic** [comment]
Sorry. I've been on holiday without my Linux laptop. 
This is what I see if I right-click an application:
![menu1](https://cloud.githubusercontent.com/assets/1222693/22002775/878338b8-dc1c-11e6-89d1-044e9cfdab49.png)

Atom was installed with apt-get so I would like to be able to uninstall it from the context menu directly instead of opening the package manager or the command line.

If I open alacarte I can see the properties of the launcher.
e.g. for IDEA it was manually added in /opt.

![menu2](https://cloud.githubusercontent.com/assets/1222693/22002861/39cc7764-dc1d-11e6-8b88-1f82b7a36444.png)

However, when I upgrade to a newer version I want to edit the launcher file to point to a new dir.
It is easier to find the launcher using the menu search than launching alacarte and looking through the sub-menus.

The about says CinnXPStarkMenu but no version number.
Is there a newer version now?
Can you link to Odyseus custom menu so I can take a look at that?

**Comment by NikoKrause** [comment]
Does the Cinnamon menu show the same context menu without install?
I have to check that. Never seen this before.

I don't know if it's possible to open the launcher from the context menu. I'll check that for the new version.
It should be possible. I'll look into how the quicklauncher app does this.

CinnXPStarkMenu is the name I used before. Plesse install the newest version from github.
I have no version numbers. But soon the applet should be available through cinnamon spices.
But the website is still frozen.

Odyseus menu is available on cinnamon spices, which means you can install it by rightclick on a panel, then click on Add applet to panel, and there Available applets (online), search for Custom Cinnamon Menu.
https://cinnamon-spices.linuxmint.com/applets/view/264
The menu has an option "Show \"Edit .desktop file\" on context" in the settings. Check it out.
Also if it has the same problem with atom.

**Comment by NikoKrause** [comment]
Is the `Uninstall` button only missing for Atom?
Also, how did you installed Atom? Are you using a PPA?
I want to test, if this happens on my machine as well.

**Comment by opticyclic** [comment]
The `Uninstall` button isn't present for any application.

I installed atom via a deb
https://atom.io/

I have tested the issue with standard packages too.

What is interesting though is that the same issue appears in the Custom Cinnamon Menu.
I can change the settings to have several different items on the context menu but the Uninstall option never appears.
![menu3](https://cloud.githubusercontent.com/assets/1222693/22047459/424ee696-dcf5-11e6-84bb-5d5b956ee657.png)

System details

    Kernel: 4.4.0-53-generic x86_64 (64 bit gcc: 5.4.0)
    Desktop: Cinnamon 3.2.2 (Gtk 3.18.9-1ubuntu3.1+zorin1) dm: gdm3 Distro: Zorin 12 xenial

**Comment by NikoKrause** [comment]
That's weird. But the default menu has this button?

Are you using ZorinOS with Cinnamon?
There's already Cinnamon 3.2.7.

**Comment by Odyseus** [comment]
Hello, g@ys.

@opticyclic: The only way for that context menu item to not show is if you have missing the **/usr/bin/cinnamon-remove-application** file. That's the only *dependency* for that item. And based on your distribution, it seems that the **/usr/bin/cinnamon-remove-application** file is present only on Linux Mint distributions, because in Archlinux, that menu item also doesn't show up. Looking at that Python script, it isn't possible to add it to any other non-Debian distribution, because the script uses Synaptic to remove applications.

**Comment by NikoKrause** [comment]
But if he installed Atom via a .deb file,
doesn't it mean, that he uses a Debian based distro?

@opticyclic, which OS do you use? Does the default menu shows uninstall?

Also have you checked the Edit button from Odyseus menu. Is this something you wanted?

**Comment by opticyclic** [comment]
I am using ZorinOS which is is based on Ubuntu 16.04.
I am pretty sure I installed cinnamon from the repos as I don't have a ppa for it.

The default menu doesn't have it.
This is probably for the reason that @Odyseus said - There is no /usr/bin/cinnamon-remove-application file.
I wonder why/how it didn't get added if it was installed from the repos.

The edit button from @Odyseus is pretty much what I wanted although it would be cooler if it opened in alacarte or some other GUI rather than a text editor. But that is me always wanting the moon on a stick :)

**Comment by ghost** [comment]
Hi like @Odyseus said, this only appear on Mint. This need to be done by distros, because the packaging are distro specific.

Configurable Menu have his own script, that donot depend of a distro, because have 3 specific backend one for debian, another for arch and another for fedora. They are base on apt-daemon, the base library for pacman and pakagekit.

**Comment by Odyseus** [comment]
Hello, everybody.

@opticyclic

> I wonder why/how it didn't get added if it was installed from the repos.

Like we said, the **/usr/bin/cinnamon-remove-application** is found on Linux Mint systems only. It's part of the package called **mint-common** and it isn't even a file, it's just a symlink to another file (**/usr/lib/linuxmint/common/mint-remove-application.py**).

Like I mentioned before, that Python script uses Synaptic. Synaptic comes installed by default on Mint systems and not installed on Ubuntu systems, for example. Furthermore, the Synaptic package used in Mint is a modified version. Who knows if the Synaptic packages of other distributions have the command line arguments used by the **/usr/bin/cinnamon-remove-application** script? This is just an speculation since I'm not familiar with Synaptic's command line.

> The edit button from @Odyseus is pretty much what I wanted although it would be cooler if it opened in alacarte or some other GUI rather than a text editor.

I like to keep things simple and at the same time "powerful". Trying to make it work with a menu editor would have been a nightmare, because all menu editors work in different ways and all are equally buggy. Plus, they all are very limited. By directly opening the .desktop file itself, you have at your fingertips absolutely all the control. For me, the latter is more valuable than a bugged and limited GUI.

@lestcape

I will answer you here the comment you made on a Cinnamon issue.

> @Odyseus the cinnamon installer that you fork will not work, it's in development, the last release version it's what configurable menu download. You can continues forking all and I have not problem with it, but i will not remove anything from my repositories, and certainly I'm on gnome shell now and i'm moving all things and also all cinnamon behaviors and the ui code and the applets and desklets code to gnome shell... But thats not mean i will remove my repositories.

When I saw that you were removing your xlets and closing your issues, I said to myself *I'm gonna fork some of his repositories before he "lose his marbles" and start to delete them too!!!* (LOL).

I forked you Cinnamon installer repository to see if I could create a simple Python script so I can add to my menu an *Uninstall* function that could work on several Linux distributions. At first glance, it all looks a lot complicated for my level of knowledge. I will study it a little bit more before I consider adding it to my applet. Because this is a complex and delicate task (uninstalling an application with privileges) and I wouldn't want to make no mistake in the process.

**Comment by ghost** [comment]
@Odyseus there are really not problem. What I'm doing it's fork cinnamon as a whole... Cinnamon will be a gnome shell extension, so my applets and desklets will run inside gnome shell without change anything... But not only my applet and desklets also the cinnamon applets and desklets will run as they are inside gnome shell... The installation process will convert the import.gi.Cinnamon to import.gi.Shell... and also other things that need to be converted... I'm moving the cinnamon panels to gnome shell right now. This is the first step. When i have the cinnamon panels i will move the extension, then the applets and finally the desklets. Thats of course will not be a pure cinnamon, but will look like and works pretty similar. The idea it's create the infrastructure of cinnamon inside gnome shell.  So, i will not change or remove my code. In case i will need to do something i will tell you if you want.
