### ISSUE TITLE
Allow to change font size

### ISSUE THREAD

**Issue by gsantner** [NikoKrause/CinnVIIStarkMenu#31]
Please allow to change font sizes in the applet's settings. Currently there seems to be no way to change the font size of the sidebar items (Home, Downloads, ...)

**Comment by NikoKrause** [comment]
The sidebar buttons have the same font size as the favorite/applications/category buttons, don't they?

Why do you want it to have another fontsize. Does Win7 or MATE Menu has this feature?

**Comment by gsantner** [comment]
No, they don't. They are always in the same font size. I changed the size value to very big for the screenshot:
![bildschirmfoto vom 2017-06-03 01-05-42](https://cloud.githubusercontent.com/assets/6735650/26747840/e01979f4-47f8-11e7-846c-1cc3536e3cc3.png)



Because sometimes it is difficult to read :) . Sidebar, Applications/Favourites button and the app menu are always small.

> Does Win7 or MATE Menu has this feature?

At least they respect system settings about font size. If they do or do not have a seperate feature shouldn't matter - Is it bad to have features that others don't? Don't think so

**Comment by NikoKrause** [comment]
> At least they respect system settings about font size.

What about the default menu of Cinnamon?
Does it respect system settings font size?

>They are always in the same font size. I changed the size value to very big for the screenshot:

I'm confused.
You changed the icon size not the font size.

Why do you want just to change the font size of the sidebar buttons, but not the others. Wouldn't that look weird?

**Comment by NikoKrause** [comment]
You say
> Because sometimes it is difficult to read :) . 

And 

> At least they respect system settings about font size.

Do you use HDPI Monitor, because you can't read them? Do the other applets of yours have a different font size?

I never changed the font size in the system settings, where do I find this?

If you say, that the menu doesn't respect the font size of the system settings, but other applets (especially the Cinnamon menu) do, than that's a bug and should be fixed.

But if all applets (wifi, menu, sound, etc) have the same font size and you have trouble to read those, than that's another problem.

**Comment by Odyseus** [comment]
Hello, everybody.

@gsantner: The menu (this one, the default and every single applet that has a menu) doesn't respond to font size settings because the font size for the menu is (or might be) hard coded in the Cinnamon theme that you are using.

You have several options at hand.

1. Edit you Cinnamon theme.
2. Follow [this instructions](https://forums.linuxmint.com/viewtopic.php?f=208&t=230128#p1217325).
3. Set the option called **Text scaling factor**.

**Comment by gsantner** [comment]
@Odyseus  thanks for your comment, I'm looking into it

**Comment by NikoKrause** [comment]
Nice to know!

**Comment by NikoKrause** [comment]
What about this?
https://sites.google.com/site/easylinuxtipsproject/mint-cinnamon-first#TOC-Increase-general-font-size-and-cursor-size
(item 3.12, right column)
