### ISSUE TITLE
Applet is 'Not Suitable For Vertical Panels' on Cinnamon Unstable

### ISSUE THREAD

**Issue by dominichayesferen** [NikoKrause/CinnVIIStarkMenu#7]
@NikoKrause 
Turns out the applet is incompatible with Vertical Panels in Cinnamon 3.0.7 DEV. You might want to use some code from menu@cinnamon.org to fix this as that applet works on vertical panels fine...

**Comment by NikoKrause** [comment]
@feren 
Yes, they (the Linux Mint team) did the vertical panel just a few days ago. It's very easy to fix, i.e. just a few lines of code.
I'll try it out very soon. I hope though, that it doesn't break for Linux Mint 17.3.

**Comment by NikoKrause** [comment]
@feren 
Hey, I added the code from the menu@cinnamon.org applet for the vertical panels.
I don't use the latest Cinnamon, so I don't know if it fixes your problem.
Can you test it and tell me your result?

**Comment by dominichayesferen** [comment]
@NikoKrause 
Not right now, Live CD HDD died, so you'll have to test it in a VM or somewhere else for now... :/

**Comment by NikoKrause** [comment]
Okay, let me now after you tested. Hope you didn't lost any important data.

**Comment by dominichayesferen** [comment]
This, Basically, is the damage:
- feren OS Stable Development
- The Latest Stable ISO
- Linux Mint 18 ISO
- feren OS Constructor
- Some useful stuff

**Comment by cinnamoner** [comment]
@NikoKrause @feren 
Yes. The default Cinnamon menu is bulky and unpleasant. The Starkmenu is therefore very important to me. Thanks Niko for continuously improving it. I'll try to look into the issue opened by feren asap and provide some feedback.

**Comment by dominichayesferen** [comment]
@cinnamoner 
If you want Vertical Panels, on your Mint 18 machine, add this PPA:
`sudo add-apt-repository ppa:gwendal-lebihan-dev/cinnamon-nightly`

Then just check for and update all packages to then be able to test it on Vertical Panels
DISCLAIMER: If you find any bugs (apart from not being able to unlock if the user has no password (I reported that)), make an issue on Cinnamon's GitHub page (or Nemo or cinnamon-screensaver depending on what part of the DE has the bug in it) about it including how to reproduce, etc)

**Comment by NikoKrause** [comment]
I tested vertical panels with CinnXPStarkMenu. It works :)
So I am about to close the very first issue for this repository ;)

**Comment by NikoKrause** [comment]
@feren 
I tested the vertical panel with the PPA you mentioned above.
I saw that Linux Mint has "unstable packages (romeo)". 
Is there a difference between romeo and the PPA you named?

**Comment by cinnamoner** [comment]
@NikoKrause Feren is offline at this hour. Thanks for continuously improving the applet.

**Comment by Elbullazul** [comment]
@NikoKrause Romeo is for official "unstable" sources; but they have been tested extensively by Mint's testing program (romeo)

I guess the PPA is from a guy who maintains the latest nightly builds for cinnamon (no testing)

glad the menu works :D 

would you mind posting a screenshot to see how it looks?

**Comment by dominichayesferen** [comment]
@NikoKrause The PPA is literally builds at GitHub-added stage of development
@Elbullazul It will be next to the panel

**Comment by NikoKrause** [comment]
Here you go:
![bildschirmfoto vom 2016-09-14 10-25-46](https://cloud.githubusercontent.com/assets/8415124/18505066/c9e722fa-7a65-11e6-862e-f546e5a283b0.png)

**Comment by cinnamoner** [comment]
@NikoKrause Aha. Looks interesting. Don't draw from Romero, unless you're prepared to crash your system.

**Comment by NikoKrause** [comment]
@feren @Elbullazul @cinnamoner 
You are having quite a few different projects ongoing. Can you give me a quick overview about them?
What are Longhorn, ferenOS, RedmondThemes, Cinn7, etc.?

**Comment by Elbullazul** [comment]
well, since @feren has taken a small break, I'll try to explain
- FerenOS is feren's biggest project to date, a mint-based Linux distro. He's built some apps and integrated some others from other DEs to achieve his "perfect Linux environment".
- Longhorn is a collab between he and me to port the biggest of Windows Longhorn theme's. Have a preview [here](http://b00merang.weebly.com/longhorn-themes)
- Cinn7 is @feren's own implementation of my Se7en Cinnamon theme, except it's friendly with all kinds of wallpapers, unlike mine who looks nicer with blue backgrounds
- Redmond Themes is an adaptation of all Windows themes since 3.x up to 10 (and beyond!), which I maintain and @feren helps with suggestions, bug reports, etc. All themes have a preview [here](http://b00merang.weebly.com/redmond-collection.html)

**Comment by Elbullazul** [comment]
also, if you're wondering, [B00merang TransPack](https://github.com/B00merang-Project/TransPack) is a script for easy installation and application of our Windows 10 theme. In the future, we hope to make it compatible with all Windows (and why not macos & chrome themes too?) themes.

**Comment by cinnamoner** [comment]
@NikoKrause Yeah, in a nutshell that's pretty much what Elbu laid out. I take this occasion to thank you for the effort you've invested into StarkMenu.

**Comment by NikoKrause** [comment]
I tried to make a bootable USB-Stick for ferenOS.
No operating system found. I used the default USB-Imagecreatortool from Linux Mint, which usually works great. Any suggestions (no CD)?

**Comment by Elbullazul** [comment]
that app doesn't work great lately, maybe try doing it from a windows machine (if available)?

**Comment by BigDaddyLinux** [comment]
@NikoKrause Etcher works great and is an appimage so you don't even need to install it
https://etcher.io/

**Comment by dominichayesferen** [comment]
@NikoKrause I ended up using Universal USB Installer here...

**Comment by dominichayesferen** [comment]
Dunno why it doesn't work

**Comment by NikoKrause** [comment]
@feren 
Unetbootin did the trick.
I just had a quick peek (about 10 min) at ferenOS. It has a lot of options!
As a new user, some questions that popped into my mind, while using.
First, it's hard to find the shut down button. The menu doesn't has one. The user-applet, which has that, is hidden under the collapsible systray icon. I think it's possible to search in the menu for "quit"? Imo it's not very intuitive to find the button.

(Windows/Cinnamon has a button in the menu. You are using a clone of the elementary menu, slingshot I guess? ElementaryOS has this Shutdown-Icon at the top right.)

Either way, it's a strange mix. At first it looks like Windows7, but uses the slingshot menu, which imo doesn't seem to fit together, because of the above mentioned.

Second, you have the close and the minimize button at top right, and the maximize button at the top left? Why?

Third, the icons at the panel look a little bit blurry to me. Maybe it's just my imagination? Not sure?!

All in all, it's interesting and I think for some users it's great to have an out of the box experience to get Linux look like Windows XP, 7, Vista, 10, etc. 
But it still could be polished a little bit more.

Is there a github repo, were you're chatting about ferenOS?

**Comment by dominichayesferen** [comment]
@NikoKrause 1. You can search Shutdown or other Power Commands in the menu...
2. The maximize button firstly doesn't look good inbetween close and minimise, and also, it on the left was the most common layout in the Design Concepts
3. You can use Themer to change the menu a bit easier-ly (CinnXPStarkMenu is included)
4. Have you tried Themer
5. I am working on trying to fix things, also, the feren Theme is goanna get a LOT of polish Cinnamon-wise in 2017.0 too

**Comment by dominichayesferen** [comment]
@NikoKrause Right now: https://github.com/Elbullazul/Redmond-Themes/issues/10

**Comment by cinnamoner** [comment]
> All in all, it's interesting and I think for some users it's great to have an out of the box experience to get
> Linux look like Windows XP, 7, Vista, 10, etc. 
> But it still could be polished a little bit more.

@NikoKrause I like your eye for details. You're a perfectionist just like me.  👍👍👍

**Comment by cinnamoner** [comment]
@feren Think of a strategy to convince Clem to put Stark as default in upcoming Serena.

**Comment by NikoKrause** [comment]
That's never going to happen. I wouldn't want it to. 
The original menu is minimalistic and it gets the job done well.
Stark has to many options. It's good as a third party applet.
I still want to change some stuff in Stark. Changing the name. One or two features. Removing bugs. Getting rid of some warnings. (I would like to remove the DropDown Option for the shutdown menu. I don't like how the menu jumps, when it's opening. But I don't want to dissapoint the people, who are used to it.)
Cleaning the settings, there is now a new option for that since LM18. I think this will break it for LM17.
But I don't know, when I'm getting to this. Have some other projects right now. Probably for Cinnamon 3.4.
But when it's done, I'll tag it as the first release. And I want to upload it on the spices Website. Still waiting for the new webdesign :)

**Comment by Elbullazul** [comment]
@NikoKrause what was the code you used for vertical panels?

**Comment by NikoKrause** [comment]
What do you need it for?

**Comment by Elbullazul** [comment]
I want to make slingshot work on vertical panels. It renders OK, it's just cinnamon not wanting it to load

**Comment by NikoKrause** [comment]
This one?
https://cinnamon-spices.linuxmint.com/applets/view/197

**Comment by Elbullazul** [comment]
@NikoKrause yes, I have already made the mods I wanted (add a shutdown button), and next feature on list is compatibility with vertical panels

https://github.com/feren/ferenOSProjectUpdates/issues/4

**Comment by NikoKrause** [comment]
There are two commits, I used for that:
The first one was
https://github.com/linuxmint/Cinnamon/commit/159f1f1a62f430caf3c1eb72081c319d6c00d5e5
and the second was
https://github.com/NikoKrause/CinnVIIStarkMenu/commit/80f559aa04df34f3216ec612586441c960d5f60c

**Comment by dominichayesferen** [comment]
@NikoKrause @Elbullazul I've got it (kinda) working on Vertical Panels on the released 2017.0 Builds (It's a fork though), but, as you'll see if you try the Ubuntu Theme in Themer, my try at it has it sometimes NOT move from Horizontal <> Vertical Panels...
