### ISSUE TITLE
improve peformance

### ISSUE THREAD

**Issue by fortalezense** [NikoKrause/CinnVIIStarkMenu#8]
The Cinnamon stock menu is great. It uses directional detection in order to provide a better navigation. You can read a lot of good information here: https://github.com/linuxmint/Cinnamon/issues/1775
But to implement directional detection, Cinnamon draws a polygon (a vector box) in the menu. That uses precious resources. @lestcape created other solution for this feature that seems to be more efficient. You can read about it here: https://github.com/linuxmint/Cinnamon/issues/4464 and here: https://github.com/linuxmint/Cinnamon/issues/4854

So I suggest implementing lestcape's solution into CinnXPStarkMenu.

**Comment by ghost** [comment]
That's true, but i generalized the vectorbox detection for be used in global menu, and that solution won work nice in all context yet... The initial solution in the spice website then will be better to be adapted to an specific context like that... so, if you want to do that i recommended to use the initial solution as is more easy to be adapted.

The idea it's replace the polygon by mathematics without the existence of a real polygon, this really increase the performance a lot as a real polygon demand the usage of gl on a motion event i.e. whatever that mouse move require a recalculation of the polygon area and the repaint of the polygon using gl.

**Edit:**
We are talking about this polygon:
https://github.com/NikoKrause/CinnXPStarkMenu/blob/master/applet.js#L3083

**Comment by NikoKrause** [comment]
Till now I never knew, what the vectorBox was for.
@lestcape 
It seems that you are far more familiar with this problem (and a solution for it) than I am.
I saw your bug report, which hasn't got any response since more than one year.
To me it sounds you have already a solution to improve the performance of the menu.
I would appreciate, if you would adapt it to the original cinnamon menu and would create a PR for it.
I'm sure this way it will get more attention and the original menu will benefit from your work as well.

**Comment by ghost** [comment]
No way... Feel free to do what you want... If this will be interesting for cinnamon i will get a response in that thread not? It's not there so I'm waiting for a response...

**Comment by ghost** [comment]
In my point of view no one want a change of his code, if it's not for a clear fix, If you change something this yours for the century... I have also a modification of popupmenu manager that allow open several submenu at the same time in cinnamon (floating submenu). Thats in my opinion it's a really nice feature to have, but for same reason i don't want to make a change, i then working on my own popupmenu api, to forget any incompatibility with the cinnamon api and at the same time do what i want... If some one are interesting in anything there, can see the code and port it to the cinnamon api. when he want:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js

The general solution of a vector box it's also there:
https://github.com/lestcape/Global-AppMenu/blob/master/globalAppMenu%40lestcape/configurableMenus.js#L1357

**Comment by NikoKrause** [comment]
As I said, I have no clue what the vectorBox does or how it works.
To me it sounds as you already have an implementation and it wouldn't take you so long to adopt it.
We're not talking about adding a new feature, but improve performance. Which is more likely to get merged.
It would take me several days or weeks, to figure the whole thing out and to understand it. And I don't have the time right now.

**Comment by ghost** [comment]
Thats why i say If you change something this is yours for the century... because normally no one have the time to see the work of the others... In this case the change will need to be done in the most complicate session of the menu, where is decide the category and items to show. This mean, yes it's complicate to be adapted and i also don't have time to do it... When Configurable Menu will work again probably i have time to see about a non interesting menu for me (the cinnamon menu).

Finally and in any case, this is a request for you, not for me. Resolve it like you want... If you want help, you know how you can contact me.

**Comment by Odyseus** [comment]
Hello, g@ys.

I have received the same request from **fortalezense** for my Custom Cinnamon Menu and did some research on the subject. To sum up, I didn't understand anything!!! LOL

But I did some tests. I replaced all functions handling vectors from my menu by the functions used by @lestcape's Configurable Menu. As I understand it, the original menu uses an **St.Polygon** Clutter element and that's what makes the menu _slow_? The functions used by Configurable Menu doesn't use an **St.Polygon** Clutter element and that makes it faster?

@NikoKrause: in case that you want to do some tests, here is what I did.
- I removed from my menu the functions **makeVectorBox**, **maybeUpdateVectorBox**, **updateVectorBox** and **destroyVectorBox**.
- I added the following functions from lestcape's Configurable Menu: **makeVectorBox**, **maybeUpdateVectorBox**, **updateVectorBox**, **destroyVectorBox** and **isInsideVectorBox**.
- Then saved the changes and restarted Cinnamon.

I don't really see the _improved performance_. To be honest, I consider the overall performance of the default Cinnamon menu (and all of its forks) to be the fastest of all menus from all desktop environments combined. The only thing that I was finding too slow was the initial menu opening and that's why I added to my menu an option to remove the All Applications category.

**Comment by ghost** [comment]
The performance improved occurs, when you are moving inside categories, not more than that. You can not see the impact, because this is faster in cinnamon menu, like cinnamon menu do not reorder applications. If you try to change the order of application (i.e a better search inside the menu), you will see the degradation of the performance and you will see how this help.

**Comment by ghost** [comment]
@Odyseus to improve the performance on opening, i recommended, hide all actors that you can, when the menu will close and then show only the visible actors when the menu will opened and show the others on idle. This will help, for open the menu more faster when it's not the first time that you open the menu.

In the first time, what could help it's open the menu outside the screen (when it's constructed) and in idle close the menu and reposition the actor to the normal place.

This also help to open the menu more faster: https://github.com/linuxmint/Cinnamon/issues/4984

**Comment by ghost** [comment]
@Odyseus:
**As I understand it, the original menu uses an St.Polygon Clutter element and that's what makes the menu slow?** 

Yes, because cinnamon menu repaint a polygon whatever a mouse it's moving. This is a transparent polygon, to see what occurs change debug to true here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L2031

What i do it's not paint a polygon to block the signals whatever the mouse it moved (inside categories). As this change a call of GL by a simple calculation, be sure there are an improve.

**Comment by NikoKrause** [comment]
@Odyseus 
Thanks for pointing this out. I better stick with the stock solution.
I don't want to mess around with code I don't understand. Especially if the improved performance isn't really visible. Changing this will make it harder to maintain the applet in the long run. 
That's why I try to stick the code as near as possible to the stock menu.
